---
title: Curriculum Vitae
subtitle: \SunQuarTeX Examples
format:
  html: default
  pdf:
    fontsize: 10pt
---

\vspace{-1cm}

::::: {layout="[83,17]"}

::: {}
- **Name:** Usami Renko
- **Email:** [usamir@ukyoto.edu.jp](mailto:usamir@ukyoto.edu.jp)
- **Homepage:** <https://blog.usamir.top/>
:::

::: {}
\vspace{-3.2cm}
:::
:::::

## Education

### 2038/09--2042/06 | UKyoto | Bachelor of Physics

#### Grades (by the end of 6th semester)

- **GPA:** 3.9 / 4.0
- **GPA Ranking:** 3 / 233

#### Undergraduate Thesis

- **Advisor:** Prof. Yumemi Okazaki, UKyoto
- **Studying Area:** Grand Unified Theory, Supersymmetry, String Theory, Quantum Gravity

#### Awards

:::{.list-table widths="1,2,3,3"}

* - Date
  - Round
  - Award
  - Issued by

* - 2039/12
  - 2038--2039
  - Excellent Student
  - UKyoto
:::

#### Scholarships

:::{.list-table widths="1,2,3,3"}

* - Date
  - Round
  - Scholarship
  - Issued by

* - 2039/11
  - 2038--2039
  - UKyoto Scholarship for Outstanding Students
  - UKyoto

* - 2040/03
  - 2039--2040
  - Western Scholarship
  - Team Shenzhen Bob
:::

## Competitions

### GeoGuessr

:::{.list-table widths="1,3,1"}

* - Date
  - Competition
  - Prize

* - 2039/12/15
  - GeoGuessr World Championship 2039
  - 5nd Place

* - 2040/11/30
  - GeoGuessr World Championship 2040
  - 2nd Place
:::

{{< pagebreak >}}

## Talks

:::{.list-table widths="2,7,3"}

* - Date
  - Title
  - Links

* - 2040/11/30
  - **Introduction to Formal Physics with Lean 4**
  - onsite (en)
    latest (en)
* - []{colspan=3}
    - Introducing Physlib: Digitalizing Physics in Lean 4.

* - 2039/09/15
  - **Analytical Mechanics, Differential Manifolds and Symplectic Geometry**
  - onsite (en)
* - []{colspan=3}
    - UTokyo--UKyoto Student Physics Workshop
:::

## Programs

:::{.list-table widths=1,5,1}

* - Date
  - Program
  - Links

* - 2039/11--2040/12
  - **Supernatural Borders and Where to Find Them**
  - 
* - []{colspan=3}
    - Innovation and Entrepreneurship Training Program for College Students
    - We study the supernatural borders, a class of spatial boundaries that can be crossed with certain conditions. The concept is originated from the string theory, but recent investigations have provided evidence for the existence of supernatural borders in our world. We aim to systematically study the properties of supernatural borders, identify them in the real world and explore their potential applications.
    - **Role:** Project Leader
    - **Joint with:** Maribel Hearn
:::

## Skills

- **Formal Languages** General programming language familiarity. (Python / Lean 4)

- **Formalizing Physics** Contributor of Physlib 4. Work experience in formalization and annotation in Lean 4.

- **Typesetting** Experienced user of Markdown, \LaTeX, Quarto and \SunQuarTeX.

- **GeoGuesser** Top 1% player in GeoGuessr.

- **Natural Languages**:
  - **Japanese**: Native
  - **English**:
    - **IELTS Academic** 7.5 (8.5 / 8 / 6.5 / 6.5)